version: 2.1
jobs:
  semgrep-full-scan:
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run: 
          name: "check git diff origin/master"
          command: |
            git diff --cached --name-status --no-ext-diff -z --diff-filter=ACDMRTUXB --ignore-submodules --merge-base origin/master
      - run: 
          name: "check git diff master"
          command: |
            git diff --cached --name-status --no-ext-diff -z --diff-filter=ACDMRTUXB --ignore-submodules --merge-base master
      - run: 
          name: "Semgrep full scan"
          command: |
            echo "This is a semgrep full scan"
            semgrep ci
  semgrep-pr-scan:
    parameters:
      default_branch:
        type: string
        default: master
    environment:
      SEMGREP_BASELINE_REF: << parameters.default_branch >>
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run: 
          name: "check git diff origin/master"
          command: |
            git diff --cached --name-status --no-ext-diff -z --diff-filter=ACDMRTUXB --ignore-submodules --merge-base origin/master
      - run: 
          name: "check git diff master"
          command: |
            git diff --cached --name-status --no-ext-diff -z --diff-filter=ACDMRTUXB --ignore-submodules --merge-base master
      - run: 
          name: "Semgrep pull request scan"
          command: |
            echo "This is a pull request semgrep scan"
            semgrep ci --baseline-commit=$(git merge-base HEAD master)
workflows:
  version: 2
  scan:
    jobs:
      - semgrep-full-scan:
          filters:
            branches:
              only: master
          context:
            - dev
      - semgrep-pr-scan:
          filters:
            branches:
              ignore: master          
          context:
            - dev
